make test: Test both transport methods

diff --git a/test_steganos b/test_steganos
--- a/test_steganos
+++ b/test_steganos
@@ -3,10 +3,20 @@
 set -e
 
 # Size of test file
-BYTES=8192
+BYTES=${BYTES:-8192}
 
 tempdir=$(mktemp -d)
 receiver_pid=
+
+case $1 in
+	-f) method=-f ;;
+	-l) method=-l ;;
+	"") method=-f ;;
+	*)
+		echo "ERROR: Invalid method '$1', see steganos -h." >&2
+		exit 1
+		;;
+esac
 
 cleanup() {
 	echo "[INFO] Cleaning up"
@@ -21,11 +31,11 @@ trap cleanup EXIT
 dd if=/dev/urandom of=$tempdir/random_input bs=1 count=$BYTES
 
 echo "[INFO] Preparing receiver"
-./steganos -R -f > $tempdir/output &
+./steganos -R $method > $tempdir/output &
 receiver_pid=$!
 
 echo "[INFO] Transmitting data"
-time ./steganos -T -f < $tempdir/random_input
+time ./steganos -T $method < $tempdir/random_input
 
 if ! diff $tempdir/random_input $tempdir/output; then
 	echo '[ERROR] Data not transported successfully'
